export const PATIENT_DATA = [ 
    {
        img: "https://i.imgur.com/T3tayIx.jpg",
        patient_firstName: "Esthera",
        patient_lastName: "Jackson",
        sex: "Female",
        birthday: "02-12-2001",
        age: 24,
        reserved_date: "03-26-2022",
        time: "10:20 AM",
        a: 0,
        b: 0,
        c: 0,
        d: 0,
        e: 0,
        f: 0,
        g: 1,
        h: 0,
        i: 0,
        j: 1,
        k: 0,
        l: "Other detail"   
    },
    {
        img: "https://i.imgur.com/WiodOh4.jpg",
        patient_firstName: "Bruno",
        patient_lastName: "Mars",
        sex: "Male",
        birthday: "02-12-2001",
        age: 24,
        reserved_date: "03-27-2022",
        time: "10:20 AM",
        a: 1,
        b: 0,
        c: 0,
        d: 0,
        e: 0,
        f: 0,
        g: 0,
        h: 0,
        i: 0,
        j: 0,
        k: 0,
        l: null
    },
    {
        img: "https://i.imgur.com/T3tayIx.jpg",
        patient_firstName: "Maroon",
        patient_lastName: "Five",
        sex: "Male",
        birthday: "02-12-2001",
        age: 24,
        reserved_date: "03-28-2022",
        time: "10:20 AM",
        a: 0,
        b: 0,
        c: 1,
        d: 0,
        e: 0,
        f: 0,
        g: 0,
        h: 0,
        i: 0,
        j: 1,
        k: 0,
        l: "Walk like a jaguar",
        reason:"This is a test data. This is a test data. This is a test data. This is a test data. This is a test data. This is a test data. "   
    },
    {
        img: "https://i.imgur.com/WiodOh4.jpg",
        patient_firstName: "Girls",
        patient_lastName: "Generation",
        sex: "Female",
        birthday: "02-12-2001",
        age: 24,
        reserved_date: "03-29-2022",
        time: "10:20 AM",
        a: 1,
        b: 0,
        c: 0,
        d: 0,
        e: 0,
        f: 0,
        g: 0,
        h: 0,
        i: 0,
        j: 0,
        k: 0,
        l: "Gee"   
    },
    
]
