export const PATIENT_DATA = [
    {
        img: "https://i.imgur.com/oDUfOX6.png",
        first_name: "Justin",
        last_name: "Lee",
        wounded_area: "Eat too much pizza",
        available: 1,
        severity: 4,
        reserved_date: "03-26-2022",
        time: "10:20 AM",
        a: 1,
        b: 1,
        c: 0,
        d: 0,
        e: 0,
        f: 0,
        g: 1,
        h: 0,
        i: 0,
        j: 1,
        k: 0,
        l: "Other detail"   
    },
    {
        img: "https://i.imgur.com/oDUfOX6.png",
        first_name: "Justin",
        last_name: "Lee",
        wounded_area: "Eat too much pizza",
        available: 1,
        severity: 4,
        reserved_date: "03-26-2022",
        time: "10:20 AM",
        a: 1,
        b: 1,
        c: 0,
        d: 0,
        e: 0,
        f: 0,
        g: 1,
        h: 0,
        i: 0,
        j: 1,
        k: 0,
        l: "Other detail"   
    },
    {
        img: "https://i.imgur.com/oDUfOX6.png",
        first_name: "Justin",
        last_name: "Lee",
        wounded_area: "Eat too much pizza",
        available: 1,
        severity: 4,
        reserved_date: "03-26-2022",
        time: "10:20 AM",
        a: 1,
        b: 1,
        c: 0,
        d: 0,
        e: 0,
        f: 0,
        g: 1,
        h: 0,
        i: 0,
        j: 1,
        k: 0,
        l: "Other detail"   
    },
    {
        img: "https://i.imgur.com/oDUfOX6.png",
        first_name: "Justin",
        last_name: "Lee",
        wounded_area: "Eat too much pizza",
        available: 1,
        severity: 4,
        reserved_date: "03-26-2022",
        time: "10:20 AM",
        a: 1,
        b: 1,
        c: 0,
        d: 0,
        e: 0,
        f: 0,
        g: 1,
        h: 0,
        i: 0,
        j: 1,
        k: 0,
        l: "Other detail"   
    },
    {
        img: "https://i.imgur.com/oDUfOX6.png",
        first_name: "Justin",
        last_name: "Lee",
        wounded_area: "Eat too much pizza",
        available: 1,
        severity: 4,
        reserved_date: "03-26-2022",
        time: "10:20 AM",
        a: 1,
        b: 1,
        c: 0,
        d: 0,
        e: 0,
        f: 0,
        g: 1,
        h: 0,
        i: 0,
        j: 1,
        k: 0,
        l: "Other detail"   
    },
    {
        img: "https://i.imgur.com/oDUfOX6.png",
        first_name: "Justin",
        last_name: "Lee",
        wounded_area: "Eat too much pizza",
        available: 1,
        severity: 4,
        reserved_date: "03-26-2022",
        time: "10:20 AM",
        a: 1,
        b: 1,
        c: 0,
        d: 0,
        e: 0,
        f: 0,
        g: 1,
        h: 0,
        i: 0,
        j: 1,
        k: 0,
        l: "Other detail"   
    },
    {
        img: "https://i.imgur.com/oDUfOX6.png",
        first_name: "Justin",
        last_name: "Lee",
        wounded_area: "Eat too much pizza",
        available: 1,
        severity: 4,
        reserved_date: "03-26-2022",
        time: "10:20 AM",
        a: 1,
        b: 1,
        c: 0,
        d: 0,
        e: 0,
        f: 0,
        g: 1,
        h: 0,
        i: 0,
        j: 1,
        k: 0,
        l: "Other detail"   
    },
    {
        img: "https://i.imgur.com/oDUfOX6.png",
        first_name: "Justin",
        last_name: "Lee",
        wounded_area: "Eat too much pizza",
        available: 1,
        severity: 4,
        reserved_date: "03-26-2022",
        time: "10:20 AM",
        a: 1,
        b: 1,
        c: 0,
        d: 0,
        e: 0,
        f: 0,
        g: 1,
        h: 0,
        i: 0,
        j: 1,
        k: 0,
        l: "Other detail"   
    },
    {
        img: "https://i.imgur.com/oDUfOX6.png",
        first_name: "Justin",
        last_name: "Lee",
        wounded_area: "Eat too much pizza",
        available: 1,
        severity: 4,
        reserved_date: "03-26-2022",
        time: "10:20 AM",
        a: 1,
        b: 1,
        c: 0,
        d: 0,
        e: 0,
        f: 0,
        g: 1,
        h: 0,
        i: 0,
        j: 1,
        k: 0,
        l: "Other detail"   
    },
    
]